### ISSUE TITLE
CSS conflicts with numerous aspects

### ISSUE THREAD

**Issue by Aetherinox** [MrGVSV/obsidian-github-embeds#5]
I like the plugin, however, I've noticed that the plugin seems to conflict with how certain things appear.

One header I have should look like the following:
![IPInKoo](https://github.com/MrGVSV/obsidian-github-embeds/assets/118329232/3555571f-17a6-4758-8f7a-3577f3f1b035)

However, as soon as I enable this plugin
![wHSRKAQ](https://github.com/MrGVSV/obsidian-github-embeds/assets/118329232/748b81bf-dd2d-4b6c-b5dd-7208426caddf)

And that's just a regular old link to an external website.

I also noticed that the following CSS property seems to make some things way bigger than they should be:

```css
._embed-container_tpqtd_1~._embed-container_tpqtd_1{
    margin-top:var(--size-4-4)
}
```

I haven't seen exactly what it is associated to, but my embedded gits seem to be ok so far, I had to override it with
```css
._embed-container_tpqtd_1
{
    margin: auto !important;
}
```
